package group3.demonGame;

/**
 *
 * @author ja34l
 */
public class CreditFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreditFrame
     */
    public CreditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        credits = new javax.swing.JLabel();
        developers = new javax.swing.JLabel();
        elizabeth = new javax.swing.JLabel();
        zeyou = new javax.swing.JLabel();
        jay = new javax.swing.JLabel();
        uiux = new javax.swing.JLabel();
        elizabeth2 = new javax.swing.JLabel();
        zeyou2 = new javax.swing.JLabel();
        jay2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 670));
        setMinimumSize(new java.awt.Dimension(1000, 670));
        setResizable(false);

        background.setBackground(new java.awt.Color(0, 0, 0));

        credits.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        credits.setForeground(new java.awt.Color(255, 255, 255));
        credits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits.setText("CREDITS");

        developers.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        developers.setForeground(new java.awt.Color(255, 255, 255));
        developers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developers.setText("DEVELOPERS");

        elizabeth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        elizabeth.setForeground(new java.awt.Color(255, 255, 255));
        elizabeth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elizabeth.setText("Elizabeth Wu");

        zeyou.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        zeyou.setForeground(new java.awt.Color(255, 255, 255));
        zeyou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeyou.setText("Zeyou Peng");

        jay.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jay.setForeground(new java.awt.Color(255, 255, 255));
        jay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jay.setText("Jaehong Lee (Jay)");

        uiux.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        uiux.setForeground(new java.awt.Color(255, 255, 255));
        uiux.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uiux.setText("UI/UX DESIGN");

        elizabeth2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        elizabeth2.setForeground(new java.awt.Color(255, 255, 255));
        elizabeth2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elizabeth2.setText("Elizabeth Wu");

        zeyou2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        zeyou2.setForeground(new java.awt.Color(255, 255, 255));
        zeyou2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zeyou2.setText("Zeyou Peng");

        jay2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jay2.setForeground(new java.awt.Color(255, 255, 255));
        jay2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jay2.setText("Jaehong Lee (Jay)");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SPECIAL THANKS TO");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Henry Rao");

        backButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(credits, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(developers, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(elizabeth, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zeyou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(uiux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(elizabeth2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(zeyou2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jay2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        backgroundLayout.setVerticalGroup(
                backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(credits)
                                .addGap(48, 48, 48)
                                .addComponent(developers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elizabeth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zeyou)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jay)
                                .addGap(44, 44, 44)
                                .addComponent(uiux)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elizabeth2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zeyou2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jay2)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(51, 51, 51)
                                .addComponent(backButton)
                                .addContainerGap(69, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
        // close credit frame
        dispose();
        // Open menu frame
        new MenuFrame().setVisible(true);
    }// GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel background;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel developers;
    private javax.swing.JLabel elizabeth;
    private javax.swing.JLabel elizabeth2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jay;
    private javax.swing.JLabel jay2;
    private javax.swing.JLabel uiux;
    private javax.swing.JLabel zeyou;
    private javax.swing.JLabel zeyou2;
    // End of variables declaration//GEN-END:variables
}
