package group3.demonGame;

import javax.swing.JFrame;

/**
 *
 * @author ja34l
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        creditButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 670));
        setMinimumSize(new java.awt.Dimension(1000, 670));
        setResizable(false);

        title.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("THE FALLEN DEMON");

        creditButton.setBackground(new java.awt.Color(0, 204, 255));
        creditButton.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        creditButton.setText("CREDIT");
        creditButton.setBorder(null);
        creditButton.setBorderPainted(false);
        creditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditButtonActionPerformed(evt);
            }
        });

        startButton.setBackground(new java.awt.Color(153, 255, 0));
        startButton.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        startButton.setText("START");
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 153));
        quitButton.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        quitButton.setText("QUIT");
        quitButton.setBorder(null);
        quitButton.setBorderPainted(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        backgroundImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ja34l\\Downloads\\Untitled.jpg")); // NOI18N
        backgroundImage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 1000,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(610, 610, 610)
                                .addComponent(creditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(backgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 1000,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(500, 500, 500)
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(510, 510, 510)
                                .addComponent(creditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(510, 510, 510)
                                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(backgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 670,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_quitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        dispose();

        // new window pop-up for game
        JFrame gWindow = new JFrame();
        // window default appears in the middle of screen
        gWindow.setLocationRelativeTo(null);
        // close event
        gWindow.setDefaultCloseOperation(3);
        // cannot adjust the size
        gWindow.setResizable(false);
        // set caption of window
        gWindow.setTitle("276 Group 3");

        // load game
        GameManager game = new GameManager();
        gWindow.add(game);
        gWindow.pack(); // fits Jframe (game window) to
                        // game/map size (specified in GameManager)

        // let people see window (after loading game so they don't notice much wait)
        gWindow.setVisible(true);

        // start game
        game.startGame();
    }// GEN-LAST:event_startButtonActionPerformed

    private void creditButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_creditButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        // Open CreditFrame
        new CreditFrame().setVisible(true);
    }// GEN-LAST:event_creditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton creditButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
